export const t = (ko, en, vi) => ({ ko, en, vi });
const s = (id, title, paragraphs, actions, caution, refs) => ({ id, title, paragraphs, actions, caution, refs });
export const chapters = [
  {
    id: 'understanding', file: 'understanding.html', oldFile: 'chapter1.html', image: 'understanding', emoji: '🩸',
    title: t('당뇨병, 몸속에서 무슨 일이 생길까요?', 'Diabetes: what happens inside the body?', 'Đái tháo đường: điều gì xảy ra trong cơ thể?'),
    summary: t('혈당·인슐린·검사 수치를 이해하는 첫걸음.', 'Understand glucose, insulin and your test results.', 'Hiểu đường huyết, insulin và kết quả xét nghiệm.'),
    caption: t('인슐린은 근육과 지방세포의 포도당 이용을 돕습니다. 열쇠 비유는 이해를 돕는 그림이며, 모든 세포가 같은 방식으로 작동하지는 않습니다.', 'Insulin helps muscle and fat cells use glucose. The key is a teaching analogy; not all cells use this pathway.', 'Insulin giúp tế bào cơ và mỡ sử dụng glucose. Hình chìa khóa chỉ là ví dụ; không phải mọi tế bào đều dùng cơ chế này.'),
    sections: [
      s('glucose', t('혈당과 인슐린', 'Glucose and insulin', 'Đường huyết và insulin'), [t('혈당은 혈액 속 포도당의 농도입니다. 탄수화물은 소화되어 포도당 등을 만들고, 간도 공복에 포도당을 공급합니다. 췌장의 인슐린은 간의 포도당 생산을 줄이고 근육·지방세포의 포도당 이용을 돕습니다.', 'Blood glucose is the concentration of glucose in blood. Digestion supplies glucose, and the liver also releases glucose between meals. Insulin from the pancreas reduces liver glucose production and helps muscle and fat cells take up glucose.', 'Đường huyết là nồng độ glucose trong máu. Tiêu hóa cung cấp glucose; gan cũng giải phóng glucose giữa các bữa ăn. Insulin từ tuyến tụy giảm sản xuất glucose ở gan và giúp cơ, mô mỡ hấp thu glucose.')], [], t('혈관 손상은 설탕이 끈적하게 붙기 때문이 아닙니다. 지속적인 고혈당과 여러 대사·혈관 요인이 함께 작용합니다.', 'Blood vessel damage is not caused by sticky sugar coating vessels. Prolonged high glucose and other metabolic and vascular factors contribute.', 'Tổn thương mạch máu không phải do đường dính lên thành mạch. Đường huyết cao kéo dài cùng các yếu tố chuyển hóa và mạch máu góp phần gây tổn thương.'), ['diagnosis', 'kda']),
      s('types', t('1형과 2형은 다릅니다', 'Type 1 and type 2 differ', 'Típ 1 và típ 2 khác nhau'), [t('1형은 보통 자가면역으로 인슐린을 만드는 세포가 손상되어 인슐린 치료가 필요합니다. 성인에게도 생깁니다. 2형은 인슐린 저항성과 분비 기능 저하가 함께 관여하며, 유전·나이·체지방·생활환경 등 여러 요인이 작용합니다.', 'Type 1 usually involves autoimmune damage to insulin-producing cells and requires insulin treatment. It can begin in adulthood. Type 2 involves insulin resistance and impaired insulin secretion, influenced by genetics, age, body fat and living conditions.', 'Típ 1 thường do tự miễn làm tổn thương tế bào sản xuất insulin và cần điều trị insulin; bệnh cũng có thể xuất hiện ở người lớn. Típ 2 liên quan kháng insulin và giảm tiết insulin, chịu ảnh hưởng của di truyền, tuổi, mỡ cơ thể và môi trường sống.')], [], t('임신당뇨병·췌장질환·약물 관련 당뇨병도 있습니다. 이 책은 성인 전단계와 2형 관리가 중심이며 임신·1형 치료를 대신하지 않습니다.', 'Other forms include gestational diabetes and diabetes related to pancreatic disease or medicines. This book focuses on adult prediabetes and type 2, not pregnancy or type 1 treatment.', 'Còn có đái tháo đường thai kỳ, do bệnh tuyến tụy hoặc thuốc. Sách tập trung vào tiền đái tháo đường và típ 2 ở người lớn, không thay thế chăm sóc thai kỳ hoặc điều trị típ 1.'), ['diagnosis']),
      s('diagnosis', t('진단 기준과 관리 목표를 구분하세요', 'Diagnosis is different from treatment targets', 'Phân biệt chẩn đoán với mục tiêu điều trị'), [t('검사실 공복혈당 100–125 mg/dL, 75g 경구당부하검사 2시간 혈당 140–199 mg/dL, 또는 HbA1c 5.7–6.4%는 전단계 범위입니다. 당뇨병 기준은 각각 126 이상, 200 이상, 6.5% 이상입니다. 경구당부하검사는 평소 식후혈당 측정과 다릅니다.', 'Laboratory fasting glucose 100–125 mg/dL, 2-hour glucose 140–199 mg/dL after a 75-g oral glucose tolerance test, or HbA1c 5.7–6.4% are prediabetes ranges. Diabetes thresholds are 126, 200 and 6.5%, respectively. An oral glucose tolerance test is not an ordinary after-meal reading.', 'Đường huyết đói tại phòng xét nghiệm 100–125 mg/dL, sau 2 giờ uống 75 g glucose 140–199 mg/dL, hoặc HbA1c 5,7–6,4% thuộc khoảng tiền đái tháo đường. Ngưỡng đái tháo đường tương ứng là 126, 200 và 6,5%. Nghiệm pháp dung nạp glucose khác đo sau bữa ăn thông thường.'), t('명백한 증상·고혈당 위기가 없다면 보통 확인 검사가 필요합니다. 빈혈 등은 HbA1c 해석에 영향을 줄 수 있습니다. 진단은 의료진이 검사 결과를 종합해 내립니다.', 'Without unequivocal symptoms or a hyperglycemic crisis, confirmation is usually needed. Anemia and other conditions may affect HbA1c. A clinician interprets the findings together.', 'Nếu không có triệu chứng rõ ràng hoặc cơn tăng đường huyết cấp, thường cần xét nghiệm xác nhận. Thiếu máu và tình trạng khác có thể ảnh hưởng HbA1c. Bác sĩ tổng hợp kết quả để chẩn đoán.')], [t('검사표에 공복·식후·당부하검사 중 무엇인지 적어 두세요.', 'Record whether the test was fasting, after a meal or an oral glucose tolerance test.', 'Ghi rõ xét nghiệm lúc đói, sau bữa ăn hay nghiệm pháp dung nạp glucose.')], t('많은 성인에서 HbA1c 7% 미만을 고려하지만, 국내 지침·나이·저혈당 위험 등에 따라 목표가 다릅니다. 진단 기준을 내 목표로 그대로 쓰지 마세요.', 'An HbA1c below 7% is considered for many adults, but national guidance, age and hypoglycemia risk affect the target. A diagnostic threshold is not automatically your target.', 'HbA1c dưới 7% được cân nhắc cho nhiều người lớn, nhưng hướng dẫn từng nước, tuổi và nguy cơ hạ đường huyết làm thay đổi mục tiêu. Ngưỡng chẩn đoán không tự động là mục tiêu của bạn.'), ['diagnosis', 'hypoglycemia', 'kda'])
    ]
  },
  {
    id: 'prevention', file: 'prevention.html', oldFile: 'chapter8.html', image: 'prevention', emoji: '🌱',
    title: t('당뇨병 전단계, 지금 시작할 관리', 'Prediabetes: begin with achievable changes', 'Tiền đái tháo đường: bắt đầu từ thay đổi khả thi'),
    summary: t('예방·체중·재검사를 한 번에 정리합니다.', 'Prevention, weight and follow-up tests.', 'Phòng ngừa, cân nặng và xét nghiệm theo dõi.'),
    caption: t('가족과 함께 작은 행동을 정하고 검사로 경과를 확인합니다. 마른 사람도 전단계가 생길 수 있습니다.', 'Plan small changes with family and follow progress with tests. Lean people can also have prediabetes.', 'Cùng gia đình đặt thay đổi nhỏ và theo dõi bằng xét nghiệm. Người gầy cũng có thể mắc tiền đái tháo đường.'),
    sections: [
      s('risk', t('전단계는 관리할 기회입니다', 'Prediabetes is an opportunity to act', 'Tiền đái tháo đường là cơ hội hành động'), [t('전단계는 혈당이 정상보다 높지만 당뇨병 진단 기준에는 미치지 않는 상태입니다. 모두가 당뇨병으로 진행하는 것은 아닙니다. 혈당뿐 아니라 혈압·지질·흡연·생활환경을 함께 살펴야 합니다.', 'Prediabetes means glucose is above normal but below diabetes thresholds. Not everyone progresses to diabetes. Review blood pressure, lipids, smoking and daily circumstances as well as glucose.', 'Tiền đái tháo đường là đường huyết cao hơn bình thường nhưng chưa đạt ngưỡng đái tháo đường. Không phải ai cũng tiến triển thành bệnh. Cần xem xét huyết áp, lipid, hút thuốc và điều kiện sống cùng đường huyết.')], [], null, ['prevention']),
      s('goals', t('체중과 활동 목표', 'Weight and activity goals', 'Mục tiêu cân nặng và vận động'), [t('과체중·비만이고 위험이 높은 성인은 체중의 약 5–7% 이상 감량을 개인 상황에 맞춰 고려하고, 중강도 활동 주 150분을 향해 늘려갈 수 있습니다. 정상체중·노쇠·근감소가 있다면 무조건 감량하기보다 영양과 근육을 지키는 목표가 필요합니다.', 'Adults at high risk with overweight or obesity can consider individualized weight loss of about 5–7% or more and work toward 150 minutes of moderate activity weekly. With normal weight, frailty or low muscle mass, preserving nutrition and muscle may take priority over weight loss.', 'Người lớn nguy cơ cao và thừa cân hoặc béo phì có thể cân nhắc giảm khoảng 5–7% cân nặng trở lên theo tình trạng cá nhân và hướng tới 150 phút vận động mức vừa mỗi tuần. Nếu cân nặng bình thường, suy yếu hoặc ít cơ, bảo vệ dinh dưỡng và cơ có thể quan trọng hơn giảm cân.')], [t('이번 주에는 단 음료를 물로 바꾸기 또는 하루 10분 걷기 중 하나를 정하세요.', 'Choose one change this week: water instead of sugary drinks, or a ten-minute walk each day.', 'Tuần này chọn một việc: thay nước ngọt bằng nước lọc, hoặc đi bộ mười phút mỗi ngày.')], null, ['prevention', 'lifestyle', 'older']),
      s('followup', t('재검사와 예방 약물', 'Follow-up and preventive medication', 'Theo dõi và thuốc phòng ngừa'), [t('전단계는 적어도 매년 혈당 상태를 확인하는 것이 권고되며, 위험과 변화에 따라 더 자주 검사할 수 있습니다. 일부 고위험군에서는 의료진이 메트포르민 예방 치료를 고려합니다. 전단계라는 이유만으로 모두 약이 필요한 것은 아닙니다.', 'At least annual glucose assessment is recommended for prediabetes, with more frequent testing when risk or changes warrant it. Clinicians may consider metformin for selected high-risk people. Prediabetes does not mean everyone needs medication.', 'Tiền đái tháo đường nên được đánh giá đường huyết ít nhất hằng năm; có thể thường xuyên hơn khi nguy cơ hoặc tình trạng thay đổi. Bác sĩ có thể cân nhắc metformin cho một số người nguy cơ cao. Không phải mọi người đều cần thuốc.')], [t('다음 검사 날짜와 내 체중·활동 목표를 진료 때 확인하세요.', 'Agree on the next test date and your weight and activity goals at your visit.', 'Thống nhất ngày xét nghiệm tiếp theo và mục tiêu cân nặng, vận động khi khám.')], t('2형 당뇨병의 관해는 완치와 다릅니다. 통상 혈당강하제 없이 3개월 이상 HbA1c 6.5% 미만을 유지하는 상태를 말하며, 재발·합병증 추적이 계속 필요합니다.', 'Remission of type 2 is not a cure. It generally means HbA1c below 6.5% for at least three months without glucose-lowering medication; ongoing monitoring remains necessary.', 'Thuyên giảm típ 2 không phải khỏi hẳn. Thường là HbA1c dưới 6,5% ít nhất ba tháng không dùng thuốc hạ đường huyết; vẫn cần theo dõi tái phát và biến chứng.'), ['prevention', 'medicines'])
    ]
  },
  {
    id: 'medicines', file: 'medicine-basics.html', oldFile: 'chapter2.html', image: 'medicines', emoji: '💊',
    title: t('내 당뇨약의 원리와 주의점', 'Understand your diabetes medicines', 'Hiểu cơ chế và lưu ý của thuốc đái tháo đường'),
    summary: t('성분·작용기전·기대 이익·부작용을 함께 봅니다.', 'Ingredients, mechanisms, benefits and adverse effects.', 'Hoạt chất, cơ chế, lợi ích và tác dụng không mong muốn.'),
    caption: t('약은 간·췌장·장·콩팥 등 서로 다른 경로에 작용합니다. 한 알에 성분이 여러 개 들어 있는 복합제도 있습니다.', 'Medicines act through different pathways in the liver, pancreas, gut and kidneys. A combination tablet contains more than one ingredient.', 'Thuốc tác động qua các đường khác nhau ở gan, tụy, ruột và thận. Một viên phối hợp chứa nhiều hoạt chất.'),
    sections: [
      s('choice', t('약이 다른 이유', 'Why prescriptions differ', 'Vì sao đơn thuốc khác nhau'), [t('약 선택은 혈당뿐 아니라 심부전·심혈관질환·콩팥병·체중·저혈당 위험·비용을 고려합니다. 특정 SGLT2 억제제와 GLP-1 계열은 해당 연구 대상에서 심장·콩팥 이익이 입증됐지만, 모든 성분에 같은 효과를 적용하면 안 됩니다.', 'Medication choice considers heart failure, cardiovascular and kidney disease, weight, hypoglycemia and cost as well as glucose. Certain SGLT2 inhibitors and GLP-1 medicines have proven heart or kidney benefits in studied populations; those results cannot be assigned equally to every ingredient.', 'Lựa chọn thuốc xét đến suy tim, bệnh tim mạch, bệnh thận, cân nặng, hạ đường huyết và chi phí, không chỉ đường huyết. Một số thuốc SGLT2 và GLP-1 có lợi ích tim hoặc thận ở nhóm đã nghiên cứu; không thể áp dụng như nhau cho mọi hoạt chất.')], [t('약봉투의 제품명 옆에서 성분명·함량·서방형 여부를 확인하세요.', 'Check ingredient names, strength and whether the formulation is extended-release.', 'Kiểm tra tên hoạt chất, hàm lượng và dạng giải phóng kéo dài trên nhãn thuốc.')], null, ['medicines', 'cardiovascular', 'mfds']),
      s('map', t('계열별 약물 지도', 'Medicine class map', 'Bản đồ các nhóm thuốc'), [t('아래 표는 계열의 일반적인 설명입니다. 성분별 차이와 병용 주의는 ‘내 당뇨약 이해하기’에서 확인하세요. 단독 저혈당 위험이 낮은 약도 인슐린·분비촉진제와 병용하면 상황이 달라집니다.', 'The table summarizes classes. Use the ingredient tool for ingredient-specific notes and combination cautions. A low hypoglycemia risk when used alone does not mean the same risk when combined with insulin or secretagogues.', 'Bảng tóm tắt các nhóm thuốc. Dùng công cụ hoạt chất để xem lưu ý riêng và phối hợp. Nguy cơ hạ đường huyết thấp khi dùng đơn độc không đồng nghĩa với nguy cơ thấp khi phối hợp insulin hoặc thuốc kích thích tiết insulin.')], [], null, ['medicines']),
      s('formulation', t('제형·복용 시간·아픈 날', 'Formulation, timing and sick days', 'Dạng thuốc, thời điểm dùng và ngày bị bệnh'), [t('같은 성분도 일반정·서방정·주사·먹는 제형의 복용법이 다를 수 있습니다. 인슐린의 작용 시간도 성분·농도·개인에 따라 달라집니다. 먹는 세마글루타이드처럼 복용 조건이 중요한 제형은 해당 제품 설명을 따라야 합니다.', 'The same ingredient may have different instructions as immediate-release, extended-release, injectable or oral formulations. Insulin action varies with ingredient, concentration and individual factors. Follow product-specific instructions for medicines such as oral semaglutide.', 'Cùng hoạt chất có thể có cách dùng khác nhau ở dạng thường, giải phóng kéo dài, tiêm hoặc uống. Tác dụng insulin khác theo hoạt chất, nồng độ và từng người. Tuân thủ hướng dẫn riêng, chẳng hạn với semaglutide uống.')], [t('복용을 잊었을 때의 방법과 금식·수술·구토 시 계획을 미리 약사·의료진에게 받아 두세요.', 'Ask your pharmacist or clinician for missed-dose and fasting, surgery or vomiting plans in advance.', 'Xin dược sĩ hoặc bác sĩ kế hoạch khi quên liều, nhịn ăn, phẫu thuật hoặc nôn từ trước.')], t('먹지 못하거나 탈수될 때 모든 약을 일괄 유지하거나 중단하는 방식은 부적절합니다. 특히 SGLT2·메트포르민 등은 상황별 조정이 필요할 수 있고, 1형의 기저 인슐린은 임의 중단하면 위험합니다.', 'Do not apply a blanket continue-or-stop rule when unable to eat or dehydrated. SGLT2 medicines and metformin may need situation-specific changes; stopping basal insulin without guidance in type 1 can be dangerous.', 'Không áp dụng quy tắc tiếp tục hoặc ngừng tất cả thuốc khi không ăn được hay mất nước. Thuốc SGLT2 và metformin có thể cần điều chỉnh theo tình huống; tự ngừng insulin nền ở típ 1 có thể nguy hiểm.'), ['medicines', 'synjardy', 'janumet'])
    ]
  },
  {
    id: 'food', file: 'food.html', oldFile: 'chapter7.html', image: 'food', emoji: '🥗',
    title: t('식단, 무엇을 얼마나 먹을까요?', 'Food: what and how much to eat?', 'Ăn gì và ăn bao nhiêu?'),
    summary: t('금지 목록 대신 양·구성·지속 가능한 선택을 익힙니다.', 'Learn portions and sustainable choices instead of a forbidden-food list.', 'Hiểu khẩu phần và lựa chọn bền vững thay vì danh sách cấm.'),
    caption: t('접시의 절반은 비전분 채소, 4분의 1은 단백질, 나머지는 탄수화물 식품으로 시작할 수 있습니다. 개인별 필요량은 다릅니다.', 'A starting plate can be half nonstarchy vegetables, one quarter protein and one quarter carbohydrate foods. Individual needs differ.', 'Có thể bắt đầu với nửa đĩa rau ít tinh bột, một phần tư đạm và một phần tư thực phẩm chứa carbohydrate. Nhu cầu mỗi người khác nhau.'),
    sections: [
      s('plate', t('한 끼의 구성부터', 'Start with a balanced meal', 'Bắt đầu từ bữa ăn cân đối'), [t('밥·면·빵을 모두 끊어야 하는 것은 아닙니다. 비전분 채소, 생선·두부·콩·살코기, 적절한 양의 곡류를 조합하세요. 접시법은 시작 도구이며 모든 사람의 필요 열량을 계산해 주지는 않습니다.', 'You do not have to remove all rice, noodles or bread. Combine nonstarchy vegetables, fish, tofu, beans or lean protein, and appropriate grain portions. The plate method is a starting tool, not a calculation of individual energy needs.', 'Không cần bỏ hết cơm, mì hoặc bánh mì. Kết hợp rau ít tinh bột, cá, đậu phụ, đậu hoặc thịt nạc với lượng ngũ cốc phù hợp. Phương pháp đĩa ăn là công cụ bắt đầu, không tính nhu cầu năng lượng cá nhân.')], [t('한국식: 밥 양을 정하고 생선·두부와 채소 반찬을 곁들이세요. 베트남식: 쌀국수 면 양과 달게 넣는 소스·음료를 함께 살펴보세요.', 'For Korean meals, plan rice portions with fish or tofu and vegetable sides. For Vietnamese meals, consider noodle portions, sweet sauces and drinks together.', 'Với món Hàn, định lượng cơm cùng cá hoặc đậu phụ và rau. Với món Việt, xem cả lượng bánh phở hoặc bún, nước sốt ngọt và đồ uống.')], t('콩팥병·심부전·위장질환이 있으면 단백질·나트륨·칼륨·수분 등을 별도로 조정할 수 있습니다. 채소나 물도 무조건 많이 권하지 않습니다.', 'Kidney disease, heart failure or digestive conditions may require changes to protein, sodium, potassium or fluids. More vegetables or water is not always better.', 'Bệnh thận, suy tim hoặc bệnh tiêu hóa có thể cần điều chỉnh đạm, natri, kali hay dịch. Không phải càng nhiều rau hoặc nước càng tốt.'), ['lifestyle', 'kda']),
      s('carbs', t('탄수화물의 양과 질', 'Carbohydrate quantity and quality', 'Lượng và chất lượng carbohydrate'), [t('통곡물·콩·통과일은 좋은 선택이지만 양이 많으면 혈당을 올릴 수 있습니다. 과일주스와 단 음료는 쉽게 많은 당을 마시게 합니다. 과일은 통째로 적절한 양을 먹는 방향을 권하며, 갈았다는 이유만으로 모두 금지하지는 않습니다.', 'Whole grains, beans and whole fruit can be good choices, but large portions still raise glucose. Juice and sugary drinks make it easy to consume a lot of sugar. Prefer suitable portions of whole fruit; blending alone does not make every food forbidden.', 'Ngũ cốc nguyên hạt, đậu và trái cây nguyên quả có thể là lựa chọn tốt, nhưng khẩu phần lớn vẫn làm tăng đường huyết. Nước ép và nước ngọt dễ khiến uống nhiều đường. Ưu tiên lượng trái cây nguyên quả phù hợp; không cấm mọi món chỉ vì xay.')], [t('영양표시는 1회 제공량·총 탄수화물·당류를 함께 보세요. ‘무설탕’도 탄수화물이 없다는 뜻은 아닙니다.', 'Read serving size, total carbohydrate and sugars together. Sugar-free does not necessarily mean carbohydrate-free.', 'Đọc cùng khẩu phần, tổng carbohydrate và đường. Không đường không nhất thiết là không carbohydrate.')], null, ['lifestyle']),
      s('order', t('먹는 순서는 보조 전략입니다', 'Meal order is an optional supporting strategy', 'Thứ tự ăn là chiến lược hỗ trợ'), [t('채소·단백질을 먼저 먹고 탄수화물을 나중에 먹으면 일부 연구에서 식후혈당 상승이 줄었습니다. 그러나 식사량·구성을 대신할 수 없고, 장기 HbA1c 개선 효과는 단기 혈당 변화와 구분해야 합니다. 연구 대상과 식사가 달라 효과를 하나의 비율로 약속할 수 없습니다.', 'Some studies find smaller post-meal glucose excursions when vegetables and protein come before carbohydrate. This does not replace portion or food choices; long-term HbA1c effects must be distinguished from short-term glucose changes. Differences in participants and meals prevent a single promised percentage.', 'Một số nghiên cứu thấy đường huyết sau ăn tăng ít hơn khi ăn rau và đạm trước carbohydrate. Cách này không thay thế khẩu phần hay lựa chọn thực phẩm; cần phân biệt HbA1c dài hạn với thay đổi đường huyết ngắn hạn. Không thể hứa một tỷ lệ hiệu quả cho mọi người.')], [], null, ['sequence', 'sequence2026']),
      s('fasting', t('단식·저탄수화물 식단과 약', 'Fasting, low-carbohydrate diets and medicines', 'Nhịn ăn, chế độ ít carbohydrate và thuốc'), [t('지중해식·적절한 탄수화물 조절 등 여러 식사 패턴을 개인의 취향·목표에 맞출 수 있습니다. 인슐린·설폰요소제·메글리티나이드 사용자는 식사량이 줄면 저혈당 위험을 고려해야 합니다. SGLT2 복용 중 극단적 탄수화물 제한·장기 금식은 케톤산증 위험과 관련될 수 있습니다.', 'Several patterns, including Mediterranean-style eating and appropriate carbohydrate reduction, can fit individual preferences and goals. Insulin, sulfonylurea or meglitinide users must consider hypoglycemia when intake falls. Extreme carbohydrate restriction or prolonged fasting with SGLT2 medicines can increase ketoacidosis concerns.', 'Có thể điều chỉnh nhiều kiểu ăn, gồm kiểu Địa Trung Hải và giảm carbohydrate phù hợp, theo sở thích và mục tiêu. Người dùng insulin, sulfonylurea hoặc meglitinide cần chú ý hạ đường huyết khi ăn ít đi. Hạn chế carbohydrate cực đoan hoặc nhịn ăn kéo dài khi dùng SGLT2 có thể tăng nguy cơ nhiễm toan ceton.')], [t('식단을 크게 바꾸기 전 복약과 측정 계획을 의료진과 정하세요.', 'Agree on medication and monitoring plans before major dietary changes.', 'Thống nhất kế hoạch thuốc và theo dõi trước khi thay đổi lớn chế độ ăn.')], null, ['lifestyle', 'medicines', 'synjardy'])
    ]
  },
  {
    id: 'habits', file: 'habits.html', oldFile: 'chapter4.html', image: 'habits', emoji: '🌙',
    title: t('수면·스트레스·술과 담배', 'Sleep, stress, alcohol and smoking', 'Giấc ngủ, căng thẳng, rượu và thuốc lá'),
    summary: t('작은 습관을 생활에 연결합니다.', 'Build small habits into daily life.', 'Gắn thói quen nhỏ vào cuộc sống hằng ngày.'),
    caption: t('걷기와 규칙적인 수면은 일상 관리의 일부입니다. 혈당 변화는 약·식사·질병 등 여러 요인의 영향을 받습니다.', 'Walking and regular sleep are part of daily care. Glucose also depends on medication, meals, illness and other factors.', 'Đi bộ và ngủ đều đặn là một phần chăm sóc. Đường huyết còn phụ thuộc thuốc, bữa ăn, bệnh và yếu tố khác.'),
    sections: [
      s('sleep', t('잠과 스트레스를 살펴보세요', 'Review sleep and stress', 'Xem lại giấc ngủ và căng thẳng'), [t('수면의 양·질·규칙성과 스트레스는 식욕·활동·자가관리와 관련됩니다. 심한 코골이·낮 졸림은 수면무호흡 평가를 받을 이유가 됩니다. 이를 치료하면 모든 사람의 혈당이 반드시 좋아진다고 단정하지 않습니다.', 'Sleep duration, quality and regularity, and stress relate to appetite, activity and self-care. Loud snoring and daytime sleepiness warrant assessment for sleep apnea. Treatment does not guarantee improved glucose for everyone.', 'Thời lượng, chất lượng, tính đều đặn của giấc ngủ và căng thẳng liên quan ăn uống, vận động, tự chăm sóc. Ngáy lớn và buồn ngủ ban ngày nên được đánh giá ngưng thở khi ngủ. Điều trị không bảo đảm đường huyết cải thiện ở mọi người.')], [t('기상 시간을 일정하게 하고, 편안한 호흡·짧은 산책처럼 유지할 수 있는 방법을 고르세요.', 'Keep a regular wake time and choose sustainable relaxation such as comfortable breathing or a short walk.', 'Giữ giờ thức dậy đều đặn và chọn thư giãn dễ duy trì như thở thoải mái hoặc đi bộ ngắn.')], null, ['lifestyle']),
      s('alcohol', t('술은 지연성 저혈당을 일으킬 수 있습니다', 'Alcohol can cause delayed hypoglycemia', 'Rượu có thể gây hạ đường huyết muộn'), [t('알코올은 간의 포도당 공급을 방해할 수 있습니다. 특히 인슐린·분비촉진제 사용자는 빈속 음주와 다음 날 저혈당에 주의해야 합니다. 술을 마시지 않는 사람이 건강을 위해 시작할 이유는 없습니다.', 'Alcohol can interfere with liver glucose supply. Insulin and secretagogue users should consider fasting alcohol intake and hypoglycemia later, including the next day. There is no health reason for a nondrinker to start.', 'Rượu có thể cản trở gan cung cấp glucose. Người dùng insulin hoặc thuốc kích thích tiết insulin cần chú ý uống lúc đói và hạ đường huyết muộn, kể cả hôm sau. Người không uống không cần bắt đầu vì sức khỏe.')], [t('음주 계획과 측정·저혈당 대처를 의료진과 확인하세요. 금연 지원도 함께 요청하세요.', 'Discuss alcohol, monitoring and hypoglycemia plans, and ask for smoking cessation support.', 'Trao đổi kế hoạch uống rượu, theo dõi, xử trí hạ đường huyết và xin hỗ trợ bỏ thuốc lá.')], null, ['lifestyle', 'hypoglycemia']),
      s('routine', t('이번 주 한 가지', 'One change this week', 'Một thay đổi tuần này'), [t('혈당은 자신을 평가하는 성적표가 아닙니다. 식사·약·활동·수면을 함께 기록하면 변화의 원인을 진료 때 논의하기 쉽습니다. 오래 지속되는 우울감·불안·관리 부담은 도움을 받을 수 있는 문제입니다.', 'Glucose is not a personal grade. Recording meals, medicines, activity and sleep helps you discuss changes at visits. Persistent low mood, anxiety or diabetes distress deserves support.', 'Đường huyết không phải điểm đánh giá con người bạn. Ghi bữa ăn, thuốc, vận động và giấc ngủ giúp trao đổi khi khám. Buồn bã, lo âu hoặc gánh nặng quản lý kéo dài cần được hỗ trợ.')], [t('작은 행동 하나와 다음 진료 때 물어볼 질문 하나를 정하세요.', 'Choose one small action and one question for your next appointment.', 'Chọn một hành động nhỏ và một câu hỏi cho lần khám tới.')], null, ['lifestyle'])
    ]
  },
  {
    id: 'exercise', file: 'exercise.html', oldFile: 'chapter5.html', image: 'exercise', emoji: '🚶',
    title: t('걷기와 근력운동, 안전하게 시작하기', 'Start walking and strength exercise safely', 'Bắt đầu đi bộ và tập sức mạnh an toàn'),
    summary: t('적은 양부터 늘리고 복약·발 상태를 함께 확인합니다.', 'Start small and consider medicines and foot health.', 'Bắt đầu ít và chú ý thuốc cùng tình trạng bàn chân.'),
    caption: t('걷기와 의자에서 일어나기는 시작 예시입니다. 통증·균형·합병증에 따라 지지와 강도를 조절하세요.', 'Walking and chair sit-to-stand are starting examples. Adjust support and intensity for pain, balance and complications.', 'Đi bộ và đứng lên từ ghế là ví dụ khởi đầu. Điều chỉnh hỗ trợ, mức tập theo đau, thăng bằng và biến chứng.'),
    sections: [
      s('mechanism', t('운동이 돕는 이유', 'Why activity helps', 'Vì sao vận động có ích'), [t('근육 수축은 인슐린 작용과 별개의 경로로 포도당 흡수를 돕습니다. 꾸준한 활동은 인슐린 감수성·체력·기능을 개선합니다. 운동은 식사·약물과 함께 쓰는 관리 수단이며, 항상 혈당이 즉시 내려가는 것은 아닙니다.', 'Muscle contraction supports glucose uptake through pathways partly separate from insulin signaling. Regular activity improves insulin sensitivity, fitness and function. Exercise complements food and medication; glucose does not always fall immediately.', 'Co cơ hỗ trợ hấp thu glucose qua các đường phần nào tách biệt tín hiệu insulin. Vận động đều cải thiện nhạy insulin, thể lực và chức năng. Tập luyện bổ sung cho ăn uống và thuốc; đường huyết không phải luôn giảm ngay.')], [], null, ['lifestyle']),
      s('amount', t('주간 목표와 시작량', 'Weekly goals and a starting dose', 'Mục tiêu tuần và mức khởi đầu'), [t('많은 성인에서 중강도 유산소 주 150분 이상, 비연속일 근력운동 주 2–3회를 권고합니다. 유산소 활동은 주 3일 이상에 나누고 이틀을 넘게 연속 쉬지 않도록 합니다. 목표에 못 미쳐도 현재보다 조금 움직이는 것부터 시작하세요.', 'Many adults are advised to aim for at least 150 minutes of moderate aerobic activity weekly and strength exercise on 2–3 nonconsecutive days. Spread aerobic activity over at least three days, with no more than two consecutive inactive days. Begin above your current activity level even if below the target.', 'Nhiều người lớn được khuyên hướng tới ít nhất 150 phút hoạt động aerobic mức vừa mỗi tuần và tập sức mạnh 2–3 ngày không liên tiếp. Chia aerobic ít nhất ba ngày, không nghỉ quá hai ngày liên tiếp. Bắt đầu tăng hơn hiện tại dù chưa đạt mục tiêu.')], [t('식후 편안한 걷기 10분부터 시도하고, 오래 앉아 있다면 약 30분마다 잠깐 움직이세요.', 'Try ten minutes of comfortable walking after a meal, and interrupt long sitting about every 30 minutes.', 'Thử đi bộ thoải mái mười phút sau ăn và ngắt thời gian ngồi lâu khoảng mỗi 30 phút.')], null, ['lifestyle']),
      s('strength', t('집에서 하는 근력운동', 'Strength exercise at home', 'Tập sức mạnh tại nhà'), [t('의자에서 일어나기, 벽 밀기, 밴드 당기기, 지지한 뒤꿈치 들기 중 안전한 동작을 고르세요. 초보자는 적은 반복·세트로 시작해 자세가 안정되면 늘립니다. 숨을 참지 말고, 의자는 움직이지 않는 것을 사용하세요.', 'Choose safe movements such as chair sit-to-stand, wall push-ups, band rows or supported heel raises. Begin with few repetitions and sets, then increase once the movement is stable. Breathe normally and use a stable chair.', 'Chọn động tác an toàn như đứng lên từ ghế, chống đẩy tường, kéo dây hoặc nhón gót có hỗ trợ. Bắt đầu ít lần, ít hiệp rồi tăng khi động tác vững. Không nín thở và dùng ghế chắc chắn.')], [], t('발 궤양이 있으면 체중부하 운동을, 증식망막병증이 있으면 고강도·힘주기 운동을 의료진과 먼저 논의하세요. 수영도 상처가 있는 발에 자동으로 안전한 대안은 아닙니다.', 'Discuss weight-bearing exercise with an active foot ulcer, and strenuous or straining exercise with proliferative retinopathy. Swimming is not automatically safe for an open foot wound.', 'Nếu loét chân đang hoạt động, trao đổi trước về tập chịu lực; nếu bệnh võng mạc tăng sinh, trao đổi về tập nặng hoặc gắng sức. Bơi không tự động an toàn khi có vết thương hở ở chân.'), ['lifestyle', 'feet']),
      s('low', t('약물별 저혈당 대비', 'Prepare according to medication risk', 'Chuẩn bị theo nguy cơ của thuốc'), [t('인슐린·설폰요소제·메글리티나이드 사용자는 운동 전후 혈당과 지연성 저혈당을 고려해야 합니다. 운동 전 탄수화물 보충은 혈당·활성 인슐린·운동 시간에 따라 달라집니다. 하나의 수치를 모든 사람에게 적용하지 않습니다.', 'Insulin, sulfonylurea and meglitinide users should consider glucose before and after activity and delayed hypoglycemia. Pre-exercise carbohydrate needs depend on glucose, active insulin and activity duration. One threshold does not fit everyone.', 'Người dùng insulin, sulfonylurea và meglitinide cần xem đường huyết trước, sau tập và hạ đường huyết muộn. Nhu cầu carbohydrate trước tập phụ thuộc đường huyết, insulin còn tác dụng và thời gian vận động. Không dùng một ngưỡng cho mọi người.')], [t('응급 포도당을 휴대하고 새 운동의 측정 계획을 정하세요. 흉통·심한 어지러움·호흡곤란이면 중단하고 도움을 받으세요.', 'Carry rapid glucose and agree on a monitoring plan for new activity. Stop and seek help for chest pain, severe dizziness or breathing difficulty.', 'Mang glucose hấp thu nhanh và thống nhất kế hoạch theo dõi cho hoạt động mới. Dừng và tìm trợ giúp nếu đau ngực, chóng mặt nặng hoặc khó thở.')], t('고혈당과 케톤이 있거나 몸이 심하게 아프면 운동으로 혈당을 억지로 낮추려 하지 마세요.', 'Do not try to force glucose down through exercise when unwell with high glucose and ketones.', 'Không cố dùng vận động để hạ đường huyết khi bệnh nặng, đường huyết cao và có ceton.'), ['lifestyle', 'hypoglycemia'])
    ]
  },
  {
    id: 'safety', file: 'safety.html', oldFile: 'chapter6.html', image: 'safety', emoji: '🧭',
    title: t('저혈당·아픈 날·검사 실전 가이드', 'Low glucose, sick days and monitoring', 'Hạ đường huyết, ngày bị bệnh và theo dõi'),
    summary: t('가족과 함께 읽어둘 대처와 진료 준비.', 'Actions and visit preparation to review with family.', 'Xử trí và chuẩn bị khám nên đọc cùng gia đình.'),
    caption: t('저혈당 때 당분을 먹는 대처는 의식이 있고 안전하게 삼킬 수 있을 때만 적용합니다. 그림의 정제 개수는 용량을 뜻하지 않습니다.', 'Oral glucose is only for someone awake and able to swallow safely. The illustrated tablet count is not a dose.', 'Chỉ cho glucose uống khi người bệnh tỉnh và nuốt an toàn. Số viên trong hình không biểu thị liều.'),
    sections: [
      s('15-15', t('저혈당: 의식이 있을 때', 'Low glucose: when awake', 'Hạ đường huyết: khi còn tỉnh'), [t('70 mg/dL 미만이면 저혈당으로 대처합니다. 의식이 있고 삼킬 수 있는 성인은 빠르게 흡수되는 포도당 약 15g을 섭취하고 15분 후 다시 측정합니다. 여전히 낮으면 반복합니다. 포도당 정제·젤은 제품 표시로 15g에 해당하는 양을 확인하세요.', 'Treat glucose below 70 mg/dL as hypoglycemia. An adult who is awake and can swallow can take about 15 g of rapid glucose and recheck after 15 minutes. Repeat if still low. Use the product label to identify 15 g in glucose tablets or gel.', 'Xử trí đường huyết dưới 70 mg/dL như hạ đường huyết. Người lớn tỉnh và nuốt được có thể dùng khoảng 15 g glucose hấp thu nhanh rồi đo lại sau 15 phút; lặp lại nếu còn thấp. Đọc nhãn viên hoặc gel glucose để xác định lượng 15 g.')], [], t('아카보스 복용자는 설탕 대신 포도당을 사용하세요. 초콜릿·지방이 많은 간식은 흡수가 느립니다. 요구르트 1개나 사탕 몇 개가 모두 15g인 것은 아닙니다.', 'With acarbose, use glucose rather than table sugar. Chocolate and high-fat snacks are slower to absorb. One yogurt or a fixed number of candies does not always provide 15 g.', 'Khi dùng acarbose, dùng glucose thay đường ăn. Sô-cô-la và đồ nhiều mỡ hấp thu chậm hơn. Một hộp sữa chua hoặc số kẹo cố định không luôn cung cấp 15 g.'), ['hypoglycemia', 'acarbose']),
      s('emergency', t('의식 저하·경련은 응급 상황', 'Impaired consciousness or seizure is an emergency', 'Rối loạn ý thức hoặc co giật là cấp cứu'), [t('의식이 없거나 안전하게 삼키지 못하면 음식·음료를 먹이지 마세요. 즉시 응급 도움을 요청하고, 처방된 글루카곤이 있으면 교육받은 방법으로 사용합니다. 심한 저혈당은 혈당 숫자와 관계없이 다른 사람의 도움이 필요한 상태입니다.', 'Do not give food or drink to someone unconscious or unable to swallow safely. Call emergency services; use prescribed glucagon if available and you have been trained. Severe hypoglycemia means assistance is needed, regardless of the measured glucose.', 'Không cho ăn uống nếu bất tỉnh hoặc không nuốt an toàn. Gọi cấp cứu; dùng glucagon đã kê nếu có và đã được hướng dẫn. Hạ đường huyết nặng là cần người khác hỗ trợ, bất kể con số đo được.')], [t('가족과 응급 연락처·포도당 위치·글루카곤 사용법을 공유하세요.', 'Share emergency contacts, glucose location and glucagon instructions with family.', 'Chia sẻ số cấp cứu, chỗ để glucose và cách dùng glucagon với gia đình.')], null, ['hypoglycemia']),
      s('sick', t('아픈 날과 케톤산증', 'Sick days and ketoacidosis', 'Ngày bị bệnh và nhiễm toan ceton'), [t('구토·탈수·금식 때 약물별 계획이 필요합니다. SGLT2 사용자는 혈당이 아주 높지 않아도 케톤산증이 생길 수 있습니다. 심한 구토·복통·빠르고 깊은 호흡·의식 변화가 있으면 혈당 숫자만 보고 기다리지 말고 신속히 진료받으세요.', 'Vomiting, dehydration or fasting requires a medicine-specific plan. SGLT2 users can develop ketoacidosis without very high glucose. Severe vomiting, abdominal pain, rapid deep breathing or altered consciousness needs prompt assessment; do not wait based on glucose alone.', 'Nôn, mất nước hoặc nhịn ăn cần kế hoạch theo từng thuốc. Người dùng SGLT2 có thể nhiễm toan ceton dù đường huyết không quá cao. Nôn nhiều, đau bụng, thở nhanh sâu hoặc thay đổi ý thức cần đánh giá sớm; không chờ chỉ dựa vào đường huyết.')], [], t('수분 제한이 있는 사람에게 ‘물을 무조건 많이 마시기’를 적용하지 않습니다. 1형 인슐린·SGLT2·메트포르민의 대처는 서로 다릅니다.', 'A person with fluid restriction should not be told to drink unlimited water. Plans for type 1 insulin, SGLT2 medicines and metformin differ.', 'Không khuyên uống nước không giới hạn cho người bị hạn chế dịch. Kế hoạch với insulin típ 1, SGLT2 và metformin khác nhau.'), ['hypoglycemia', 'medicines', 'synjardy', 'janumet']),
      s('monitoring', t('측정·정기검사·진료 질문', 'Monitoring, follow-up and visit questions', 'Đo, xét nghiệm định kỳ và câu hỏi khi khám'), [t('측정 전 손을 씻고 잘 말리세요. 식후 시간은 식사 시작부터 계산합니다. mg/dL를 mmol/L로 바꿀 때는 약 18로 나눕니다. 가정용 측정기만으로 진단하지 않습니다.', 'Wash and dry hands before testing. Count after-meal time from the start of the meal. To convert mg/dL to mmol/L, divide by about 18. Home readings alone do not establish a diagnosis.', 'Rửa và lau khô tay trước đo. Tính thời gian sau ăn từ khi bắt đầu bữa. Đổi mg/dL sang mmol/L bằng cách chia khoảng 18. Không chẩn đoán chỉ bằng máy đo tại nhà.'), t('HbA1c는 목표·치료 변화에 따라 보통 3–6개월 간격을 정합니다. 2형에서는 콩팥 기능·소변 알부민, 눈·발 검사를 진단부터 평가하고 결과에 따라 주기를 조정합니다. 혈압·지질 목표도 심혈관 위험에 따라 달라집니다.', 'HbA1c is usually reviewed every 3–6 months depending on goals and treatment changes. In type 2, kidney function, urine albumin, eyes and feet are assessed from diagnosis with follow-up adjusted to findings. Blood pressure and lipid targets also depend on cardiovascular risk.', 'HbA1c thường được đánh giá mỗi 3–6 tháng tùy mục tiêu và thay đổi điều trị. Với típ 2, đánh giá chức năng thận, albumin niệu, mắt và chân từ chẩn đoán rồi điều chỉnh lịch theo kết quả. Mục tiêu huyết áp và lipid cũng theo nguy cơ tim mạch.')], [t('진료 질문: 내 목표는? 저혈당이 오면? 아파서 못 먹으면? 새 약·보충제와 같이 먹어도 되는가?', 'Ask: What are my targets? What if glucose goes low? What if I cannot eat? Can I take a new medicine or supplement with these?', 'Hỏi: Mục tiêu của tôi là gì? Nếu hạ đường huyết thì sao? Nếu không ăn được? Thuốc hoặc bổ sung mới có dùng cùng được không?')], null, ['hypoglycemia', 'kda', 'cardiovascular'])
    ]
  },
  {
    id: 'feet', file: 'feet.html', oldFile: 'chapter9.html', image: 'feet', emoji: '🦶',
    title: t('당뇨발과 합병증, 작은 신호 알아차리기', 'Feet and complications: notice small warning signs', 'Bàn chân và biến chứng: nhận biết dấu hiệu nhỏ'),
    summary: t('감각·혈류·상처와 매일의 발 확인.', 'Sensation, circulation, wounds and daily checks.', 'Cảm giác, tuần hoàn, vết thương và kiểm tra mỗi ngày.'),
    caption: t('신경 손상은 감각을 둔하게 해 작은 상처를 놓치게 할 수 있습니다. 발바닥은 거울로 확인하세요. 그림의 상처는 예시이며 사진만으로 진단할 수 없습니다.', 'Nerve damage can reduce sensation, making a small wound easy to miss. Check soles with a mirror. The wound is illustrative, not a diagnosis from an image.', 'Tổn thương thần kinh có thể giảm cảm giác khiến bỏ sót vết thương nhỏ. Dùng gương xem lòng bàn chân. Vết thương chỉ là minh họa, không dùng hình để chẩn đoán.'),
    sections: [
      s('mechanism', t('왜 상처를 놓칠까요?', 'Why can wounds go unnoticed?', 'Vì sao có thể bỏ sót vết thương?'), [t('당뇨병성 신경병증은 저림·화끈거림뿐 아니라 감각 저하도 일으킵니다. 혈류가 나쁘면 상처 회복이 어려워질 수 있습니다. ‘아프지 않다’는 이유로 상처가 안전하다고 판단하면 안 됩니다.', 'Diabetic neuropathy can cause tingling and burning, but also loss of sensation. Poor circulation can make wounds harder to heal. A painless wound is not necessarily safe.', 'Bệnh thần kinh do đái tháo đường có thể gây tê, bỏng rát và mất cảm giác. Tuần hoàn kém có thể khiến vết thương khó lành. Không đau không có nghĩa là vết thương an toàn.')], [], null, ['feet']),
      s('daily', t('매일 확인하는 방법', 'Daily foot checks', 'Kiểm tra bàn chân hằng ngày'), [t('발등·발바닥·발가락 사이에서 물집·상처·붉음·부종을 살피세요. 손거울이나 가족의 도움을 사용할 수 있습니다. 미지근한 물로 씻고 발가락 사이까지 말리며, 잘 맞는 신발을 신기 전 안쪽에 이물질이 없는지 확인하세요.', 'Check the tops, soles and between toes for blisters, wounds, redness and swelling. Use a mirror or family help. Wash in lukewarm water, dry between toes, and check inside well-fitting shoes before putting them on.', 'Xem mu chân, lòng bàn chân và kẽ ngón để tìm phồng rộp, vết thương, đỏ, sưng. Dùng gương hoặc nhờ gia đình. Rửa bằng nước ấm vừa, lau khô kẽ ngón và kiểm tra bên trong giày vừa chân trước khi mang.')], [t('맨발로 걷지 말고, 티눈·굳은살을 칼이나 약품으로 직접 제거하지 마세요.', 'Avoid barefoot walking; do not cut or chemically remove corns or calluses yourself.', 'Không đi chân trần; không tự cắt hay dùng hóa chất loại bỏ chai chân.')], t('뜨거운 찜질·족욕은 감각이 둔한 발에 화상을 일으킬 수 있습니다.', 'Hot packs or hot foot baths can burn feet with reduced sensation.', 'Chườm nóng hoặc ngâm chân nóng có thể gây bỏng khi giảm cảm giác.'), ['feet']),
      s('seek-help', t('언제 진료받아야 할까요?', 'When to seek care', 'Khi nào cần đi khám?'), [t('새로운 상처·물집·붉음·열감·부종·진물은 신속히 의료진에게 알리세요. 발열·빠르게 퍼지는 붉음·검게 변함·심하게 차갑거나 색이 변하는 발은 긴급 평가가 필요합니다. 통증이 없어도 미루지 마세요.', 'Report a new wound, blister, redness, warmth, swelling or drainage promptly. Fever, spreading redness, black discoloration or a very cold or discolored foot requires urgent assessment. Do not delay because it is painless.', 'Báo sớm vết thương mới, phồng rộp, đỏ, nóng, sưng hoặc chảy dịch. Sốt, đỏ lan nhanh, chuyển đen hoặc bàn chân rất lạnh, đổi màu cần đánh giá khẩn cấp. Không trì hoãn vì không đau.')], [], null, ['feet']),
      s('organs', t('눈·콩팥·심장도 함께', 'Eyes, kidneys and heart matter too', 'Mắt, thận và tim cũng quan trọng'), [t('눈과 콩팥 합병증은 초기 증상이 없을 수 있어 정기검사가 중요합니다. 혈당·혈압·지질·금연과 적절한 약물은 함께 관리합니다. 발 저림은 B12 결핍 등 다른 원인도 있어 진료로 구분해야 합니다.', 'Eye and kidney complications can be silent early, so follow-up testing matters. Manage glucose, blood pressure, lipids, smoking and appropriate medicines together. Tingling can also have causes such as B12 deficiency and needs assessment.', 'Biến chứng mắt và thận có thể chưa có triệu chứng lúc đầu nên cần xét nghiệm theo dõi. Quản lý đường huyết, huyết áp, lipid, bỏ thuốc lá và thuốc phù hợp cùng nhau. Tê chân còn có thể do thiếu B12 hay nguyên nhân khác, cần đánh giá.')], [], null, ['kda', 'cardiovascular', 'janumet'])
    ]
  },
  {
    id: 'supplements', file: 'supplements.html', oldFile: 'chapter3.html', image: 'supplements', emoji: '🔎',
    title: t('건강기능식품, 근거를 구분해서 보기', 'Supplements: separate evidence from promises', 'Thực phẩm bổ sung: phân biệt bằng chứng và lời hứa'),
    summary: t('혈당 개선·결핍 교정·신경 증상은 다른 목표입니다.', 'Glucose lowering, deficiency correction and nerve symptoms are different goals.', 'Hạ đường huyết, sửa thiếu chất và triệu chứng thần kinh là mục tiêu khác nhau.'),
    caption: t('논문이 있다는 사실만으로 제품의 효과가 확정되지는 않습니다. 복용 중인 약과 함께 검토하세요.', 'The existence of a study does not establish a product’s benefit. Review supplements alongside your medicines.', 'Có nghiên cứu không đồng nghĩa hiệu quả sản phẩm đã được xác nhận. Xem xét bổ sung cùng các thuốc đang dùng.'),
    sections: [
      s('evidence', t('연구의 수보다 질과 적용 대상', 'Quality and applicability, not just study count', 'Chất lượng và đối tượng áp dụng, không chỉ số nghiên cứu'), [t('메타분석도 작은 연구·편향·짧은 추적기간을 포함할 수 있습니다. 혈당 수치 변화가 합병증 예방을 의미하지는 않습니다. 연구에서 쓴 제형·용량이 시판 제품과 다를 수 있습니다. 혈당 관리를 위한 보충제의 일상적 사용을 일괄 권하지 않습니다.', 'A meta-analysis can include small, biased or short studies. A change in glucose does not prove prevention of complications. Trial formulations and doses may differ from products sold. Routine supplements for glucose management are not generally recommended.', 'Phân tích gộp có thể gồm nghiên cứu nhỏ, thiên lệch hoặc ngắn. Thay đổi đường huyết không chứng minh phòng biến chứng. Dạng và liều nghiên cứu có thể khác sản phẩm bán. Không khuyến nghị chung việc dùng bổ sung thường quy để kiểm soát đường huyết.')], [], null, ['lifestyle']),
      s('deficiency', t('결핍 교정과 혈당 치료를 구분', 'Correcting deficiency is different from treating glucose', 'Sửa thiếu chất khác với điều trị đường huyết'), [t('메트포르민 장기 사용은 B12 감소와 관련됩니다. 빈혈·손발 저림이 있거나 오래 복용했다면 검사 필요성을 논의하세요. B12·비타민 D·마그네슘 보충은 결핍과 개인 상황을 확인하고 결정해야 하며, 모두에게 혈당 개선을 약속하지 않습니다.', 'Long-term metformin use is associated with lower B12. Discuss testing with anemia, tingling or prolonged use. B12, vitamin D or magnesium supplementation should consider deficiency and individual factors; glucose improvement is not guaranteed for everyone.', 'Metformin lâu dài liên quan giảm B12. Trao đổi xét nghiệm khi thiếu máu, tê tay chân hoặc dùng lâu. Bổ sung B12, vitamin D hay magie cần xem thiếu hụt và tình trạng cá nhân; không hứa cải thiện đường huyết cho mọi người.')], [], t('콩팥 기능이 나쁘면 일부 미네랄이 축적될 수 있습니다. 검사 없이 여러 제품을 겹쳐 먹지 마세요.', 'Some minerals can accumulate with impaired kidney function. Avoid stacking products without assessment.', 'Một số khoáng chất có thể tích tụ khi chức năng thận kém. Tránh dùng chồng nhiều sản phẩm khi chưa đánh giá.'), ['prevention', 'lifestyle', 'janumet']),
      s('ala', t('알파리포산: 장기 효과는 제한적', 'Alpha-lipoic acid: limited long-term benefit', 'Acid alpha-lipoic: lợi ích dài hạn hạn chế'), [t('일부 단기 연구의 증상 개선과 장기 효과를 구분해야 합니다. 2024년 Cochrane 검토에서는 6개월 이상 치료 시 신경병증 증상에 효과가 거의 없거나 없을 가능성을 제시했습니다. ‘신경 보호가 확실하다’고 소개하기 어렵습니다.', 'Short-term symptom findings should be separated from long-term benefit. A 2024 Cochrane review found probably little or no improvement in neuropathy symptoms after six months or more. It should not be presented as proven nerve protection.', 'Cần phân biệt cải thiện triệu chứng ngắn hạn với lợi ích lâu dài. Tổng quan Cochrane 2024 cho thấy có lẽ ít hoặc không cải thiện triệu chứng thần kinh sau sáu tháng trở lên. Không nên giới thiệu là bảo vệ thần kinh đã chắc chắn.')], [], null, ['ala']),
      s('other', t('베르베린·계피·바나바·오메가-3', 'Berberine, cinnamon, banaba and omega-3', 'Berberine, quế, banaba và omega-3'), [t('일부 성분의 혈당 개선 연구가 있어도 효과의 확실성·제품 품질·상호작용을 따로 봐야 합니다. 베르베린 등을 당뇨약 대체제로 권하지 않습니다. 일반 오메가-3 보충제와 특정 처방약의 심혈관 연구 결과도 같지 않습니다.', 'Even with glucose-lowering studies, certainty, product quality and interactions need separate review. Berberine and similar supplements should not replace diabetes medicines. Cardiovascular findings for specific prescription products are not the same as findings for ordinary omega-3 supplements.', 'Dù có nghiên cứu hạ đường huyết, vẫn cần xem độ chắc chắn, chất lượng sản phẩm và tương tác riêng. Berberine và bổ sung tương tự không thay thuốc đái tháo đường. Kết quả tim mạch của thuốc kê đơn cụ thể không giống bổ sung omega-3 thông thường.')], [t('제품·성분·함량을 진료 때 보여주고, 완치·약 중단을 약속하는 광고는 피하세요.', 'Bring product, ingredient and strength details to visits; avoid advertisements promising cures or stopping medication.', 'Mang thông tin sản phẩm, hoạt chất và hàm lượng khi khám; tránh quảng cáo hứa khỏi bệnh hoặc ngừng thuốc.')], null, ['lifestyle', 'cardiovascular'])
    ]
  }
];
// Three plain-language points shown first in each topic and collected on the summary page.
// They restate the topic text above; details, exceptions and evidence stay in the sections.
const keyPoints = {
  understanding: [
    t('혈당은 피 속 포도당의 양입니다. 인슐린은 몸이 포도당을 쓰도록 돕습니다.', 'Blood glucose is the amount of glucose in your blood. Insulin helps the body use glucose.', 'Đường huyết là lượng glucose trong máu. Insulin giúp cơ thể sử dụng glucose.'),
    t('진단 기준(공복혈당 126 mg/dL 이상, HbA1c 6.5% 이상)과 나의 관리 목표는 다릅니다. 목표는 의료진과 함께 정하세요.', 'Diagnostic thresholds (fasting glucose 126 mg/dL or higher, HbA1c 6.5% or higher) are not your personal target. Set your target with your care team.', 'Ngưỡng chẩn đoán (đường huyết đói từ 126 mg/dL, HbA1c từ 6,5% trở lên) khác với mục tiêu riêng của bạn. Hãy cùng bác sĩ đặt mục tiêu.'),
    t('검사 결과에는 공복·식후·당부하검사 중 무엇이었는지 함께 적어 두세요.', 'Write down whether each test was fasting, after a meal or an oral glucose tolerance test.', 'Ghi lại mỗi lần xét nghiệm là lúc đói, sau ăn hay nghiệm pháp dung nạp glucose.')
  ],
  prevention: [
    t('당뇨병 전단계는 관리를 시작할 기회입니다. 모두가 당뇨병으로 진행하지는 않습니다.', 'Prediabetes is a chance to act. Not everyone with prediabetes develops diabetes.', 'Tiền đái tháo đường là cơ hội để hành động. Không phải ai cũng tiến triển thành đái tháo đường.'),
    t('과체중이라면 체중의 5–7% 감량과 주 150분 걷기 같은 활동을 목표로 조금씩 늘려 보세요.', 'If you are overweight, work gradually toward losing 5–7% of your weight and about 150 minutes of activity such as walking each week.', 'Nếu thừa cân, hãy dần hướng tới giảm 5–7% cân nặng và khoảng 150 phút vận động như đi bộ mỗi tuần.'),
    t('적어도 1년에 한 번은 혈당 검사를 받으세요.', 'Have your glucose checked at least once a year.', 'Kiểm tra đường huyết ít nhất mỗi năm một lần.')
  ],
  medicines: [
    t('약봉투·처방전을 사진으로 찍어 두고, 제품명 옆의 성분명을 확인하세요.', 'Take a photo of your medicine bag or prescription, and check the ingredient names next to the product names.', 'Chụp ảnh túi thuốc hoặc đơn thuốc và xem tên hoạt chất bên cạnh tên sản phẩm.'),
    t('감기약·진통제·한약·건강기능식품을 새로 먹기 전에 약사에게 “당뇨약을 먹고 있어요”라고 알리세요.', 'Before starting cold medicine, painkillers, herbal remedies or supplements, tell the pharmacist that you take diabetes medicine.', 'Trước khi dùng thuốc cảm, thuốc giảm đau, thuốc nam, thuốc bắc hoặc thực phẩm bổ sung, hãy nói với dược sĩ rằng bạn đang dùng thuốc đái tháo đường.'),
    t('수치가 좋아지거나 아파서 못 먹을 때도 약을 스스로 끊거나 바꾸지 마세요. 그럴 때의 계획을 의료진·약사에게 미리 물어 두세요.', 'Do not stop or change medicines yourself when readings improve or when you cannot eat. Ask your care team or pharmacist for a plan in advance.', 'Không tự ngừng hoặc đổi thuốc khi chỉ số tốt hơn hay khi không ăn được. Hãy hỏi trước bác sĩ hoặc dược sĩ về kế hoạch cho những lúc đó.')
  ],
  food: [
    t('밥·면을 모두 끊을 필요는 없습니다. 접시의 절반은 녹말이 적은 채소, 4분의 1은 단백질, 4분의 1은 밥·면으로 시작해 보세요.', 'You do not need to give up rice or noodles. Start with a plate that is half non-starchy vegetables, one quarter protein and one quarter rice or noodles.', 'Không cần bỏ hẳn cơm hay bún, phở. Hãy bắt đầu với đĩa ăn gồm một nửa rau ít tinh bột, một phần tư chất đạm và một phần tư cơm hoặc bún, phở.'),
    t('단 음료와 과일주스를 줄이고, 과일은 통째로 적당한 양을 드세요.', 'Cut down on sugary drinks and fruit juice; eat whole fruit in suitable portions.', 'Giảm nước ngọt và nước ép trái cây; ăn trái cây nguyên quả với lượng vừa phải.'),
    t('식단을 크게 바꾸기 전에는 약과 혈당 측정 계획을 의료진과 먼저 정하세요.', 'Before making big changes to what you eat, agree on medicine and glucose-checking plans with your care team.', 'Trước khi thay đổi lớn chế độ ăn, hãy thống nhất kế hoạch thuốc và đo đường huyết với bác sĩ.')
  ],
  habits: [
    t('매일 같은 시간에 일어나는 등 잠을 규칙적으로 하세요. 심한 코골이·낮 졸림은 진료 때 알리세요.', 'Keep regular sleep, such as waking at the same time each day. Mention loud snoring or daytime sleepiness at your visit.', 'Ngủ đều đặn, ví dụ thức dậy cùng giờ mỗi ngày. Báo bác sĩ nếu ngáy to hoặc buồn ngủ ban ngày.'),
    t('술은 다음 날까지 저혈당을 일으킬 수 있습니다. 저혈당을 일으킬 수 있는 약(인슐린·설폰요소제 등)을 쓴다면 빈속에 마시지 마세요.', 'Alcohol can cause low glucose as late as the next day. If you use medicines that can cause low glucose (such as insulin or sulfonylureas), do not drink on an empty stomach.', 'Rượu có thể gây hạ đường huyết đến tận hôm sau. Nếu dùng thuốc có thể gây hạ đường huyết (như insulin hoặc sulfonylurea), đừng uống rượu lúc đói.'),
    t('혈당은 성적표가 아닙니다. 이번 주에 할 작은 행동 하나를 정하고, 금연이 필요하면 도움을 요청하세요.', 'Glucose is not a grade. Choose one small action for this week, and ask for help to quit smoking if needed.', 'Đường huyết không phải bảng điểm. Hãy chọn một việc nhỏ cho tuần này và nhờ hỗ trợ bỏ thuốc lá nếu cần.')
  ],
  exercise: [
    t('식후 10분 편하게 걷기부터 시작하고, 오래 앉아 있다면 30분마다 잠깐 움직이세요.', 'Start with a comfortable ten-minute walk after meals, and get up briefly about every 30 minutes when sitting for long periods.', 'Bắt đầu bằng đi bộ thoải mái mười phút sau ăn và đứng dậy vận động một chút khoảng mỗi 30 phút khi ngồi lâu.'),
    t('목표는 주 150분 중강도 활동과 주 2–3회 근력운동입니다. 지금보다 조금씩 늘리면 됩니다.', 'The goal is 150 minutes of moderate activity and strength exercise 2–3 times a week. Increase little by little from where you are now.', 'Mục tiêu là 150 phút vận động mức vừa và tập sức mạnh 2–3 lần mỗi tuần. Tăng dần từ mức hiện tại.'),
    t('저혈당을 일으킬 수 있는 약을 쓴다면 포도당을 챙기세요. 가슴 통증·심한 어지러움·숨참이 있으면 바로 멈추세요.', 'If you use medicines that can cause low glucose, carry rapid glucose. Stop right away if you have chest pain, severe dizziness or trouble breathing.', 'Nếu dùng thuốc có thể gây hạ đường huyết, hãy mang theo glucose. Dừng ngay nếu đau ngực, chóng mặt nặng hoặc khó thở.')
  ],
  safety: [
    t('혈당이 70 mg/dL 미만이고 깨어 있어 삼킬 수 있다면 포도당 약 15g을 먹고 15분 뒤 다시 재세요. 여전히 낮으면 반복합니다.', 'If glucose is below 70 mg/dL and the person is awake and can swallow, take about 15 g of rapid glucose and recheck after 15 minutes. Repeat if still low.', 'Nếu đường huyết dưới 70 mg/dL và người bệnh tỉnh, nuốt được, hãy dùng khoảng 15 g glucose rồi đo lại sau 15 phút. Lặp lại nếu vẫn thấp.'),
    t('의식이 없거나 삼키지 못하면 아무것도 먹이지 말고 바로 응급 도움을 요청하세요(한국 119, 베트남 115).', 'If the person is unconscious or cannot swallow, give nothing by mouth and call emergency services right away (119 in Korea, 115 in Vietnam).', 'Nếu bất tỉnh hoặc không nuốt được, không cho ăn uống gì và gọi cấp cứu ngay (115 tại Việt Nam, 119 tại Hàn Quốc).'),
    t('심한 구토·복통·빠른 호흡이 있으면 혈당 숫자만 보고 기다리지 말고 바로 진료를 받으세요.', 'With severe vomiting, abdominal pain or fast breathing, get care promptly; do not wait based on the glucose number alone.', 'Khi nôn nhiều, đau bụng hoặc thở nhanh, hãy đi khám ngay; đừng chỉ dựa vào con số đường huyết mà chờ đợi.')
  ],
  feet: [
    t('매일 발등·발바닥·발가락 사이를 살펴보세요. 발바닥은 거울이나 가족의 도움을 받으세요.', 'Check the tops, soles and between the toes every day. Use a mirror or ask family to help with the soles.', 'Mỗi ngày xem mu bàn chân, lòng bàn chân và kẽ ngón. Dùng gương hoặc nhờ người nhà xem lòng bàn chân.'),
    t('아프지 않아도 새 상처·물집·붉어짐·부기가 보이면 빨리 진료받으세요.', 'Even if it does not hurt, get a new wound, blister, redness or swelling checked promptly.', 'Dù không đau, hãy đi khám sớm khi có vết thương mới, phồng rộp, đỏ hoặc sưng.'),
    t('맨발로 걷지 말고, 뜨거운 찜질·족욕이나 티눈·굳은살 직접 제거는 피하세요.', 'Do not walk barefoot, and avoid hot packs, hot foot baths and removing corns or calluses yourself.', 'Không đi chân trần; tránh chườm nóng, ngâm chân nước nóng và tự cắt bỏ chai chân.')
  ],
  supplements: [
    t('건강기능식품은 당뇨약을 대신하지 않습니다.', 'Supplements do not replace diabetes medicines.', 'Thực phẩm bổ sung không thay thế thuốc đái tháo đường.'),
    t('‘완치’나 ‘약을 끊을 수 있다’고 약속하는 광고는 피하세요.', 'Avoid advertisements that promise a cure or say you can stop your medicines.', 'Tránh quảng cáo hứa chữa khỏi bệnh hoặc giúp ngừng thuốc.'),
    t('먹고 있거나 먹으려는 제품은 성분·함량을 진료 때 보여주세요. 콩팥 기능이 나쁘면 특히 중요합니다.', 'Show the ingredients and strengths of products you take or plan to take at your visit, especially if you have kidney problems.', 'Mang thông tin hoạt chất và hàm lượng của sản phẩm đang hoặc định dùng khi đi khám, nhất là khi có bệnh thận.')
  ]
};
for (const chapter of chapters) chapter.key = keyPoints[chapter.id];
// Short descriptions of what each illustration shows, read by screen readers instead of repeating the caption.
const imageAlt = {
  understanding: t('안경 쓴 중년 여성이 혈당측정기를 들고 간호사의 설명을 듣는 장면. 옆에 열쇠가 근육 세포의 문을 열어 포도당 알갱이가 들어가는 그림.', 'A middle-aged woman with glasses holds a glucose meter and listens to a nurse. Beside them, a key opens a door on a muscle cell so glucose particles can enter.', 'Người phụ nữ trung niên đeo kính cầm máy đo đường huyết và nghe điều dưỡng giải thích. Bên cạnh là hình chiếc chìa khóa mở cửa tế bào cơ để các hạt glucose đi vào.'),
  prevention: t('여성이 의사와 마주 앉아 노트에 계획을 적는 장면. 옆에 가족이 함께 공원을 걷는 모습과 채소 바구니.', 'The woman sits with a doctor who writes a plan in a notebook. Beside them, her family walks together in a park, and there is a basket of vegetables.', 'Người phụ nữ ngồi cùng bác sĩ đang ghi kế hoạch vào sổ. Bên cạnh là gia đình cùng đi bộ trong công viên và một giỏ rau.'),
  medicines: t('여성이 약사와 요일별 약 정리함을 함께 보는 장면. 옆에 간·콩팥·췌장·장 그림.', 'The woman and a pharmacist look at a weekly pill organizer together. Beside them are drawings of the liver, kidneys, pancreas and intestines.', 'Người phụ nữ cùng dược sĩ xem hộp chia thuốc theo ngày. Bên cạnh là hình gan, thận, tụy và ruột.'),
  food: t('여성이 식탁에서 채소 절반, 연어와 두부, 잡곡밥이 담긴 접시로 식사하는 장면. 주변에 국, 나물, 쌈 채소, 월남쌈과 물 한 잔.', 'The woman eats from a plate with half vegetables, salmon and tofu, and mixed-grain rice. Around it are soup, vegetable side dishes, lettuce for wraps, fresh spring rolls and a glass of water.', 'Người phụ nữ ăn đĩa gồm một nửa rau, cá hồi và đậu phụ, cơm gạo lứt trộn. Xung quanh có canh, rau trộn, rau cuốn, gỏi cuốn và một ly nước.'),
  habits: t('여성이 해 질 녘 강변을 걷는 장면과, 휴대전화를 내려놓고 편안히 잠자리에 드는 장면.', 'The woman walks by a river at sunset, and settles comfortably into bed with her phone set aside.', 'Người phụ nữ đi dạo bên sông lúc hoàng hôn, và thoải mái đi ngủ với điện thoại để sang một bên.'),
  exercise: t('여성이 운동복을 입고 강변을 걷는 장면과, 의자에서 일어나는 근력운동 장면.', 'The woman walks along a riverside path in exercise clothes, and does a sit-to-stand exercise from a chair.', 'Người phụ nữ mặc đồ tập đi bộ ven sông, và tập đứng lên từ ghế.'),
  safety: t('식탁에 앉은 여성이 식은땀을 흘리며 떨고, 가족이 포도당 정제를 건네는 장면. 식탁 위에 물 한 잔, 혈당측정기, 시계.', 'The woman sits at a table, sweating and shaky, while a family member hands her a glucose tablet. A glass of water, a glucose meter and a clock are on the table.', 'Người phụ nữ ngồi ở bàn, đổ mồ hôi và run, người nhà đưa cho bà viên glucose. Trên bàn có ly nước, máy đo đường huyết và đồng hồ.'),
  feet: t('여성이 소파에 앉아 발을 살피는 장면. 신경과 작은 상처가 표시된 발 그림과, 손거울로 발바닥을 확인하는 모습.', 'The woman sits on a sofa checking her feet: a drawing of a foot with nerves and a small wound, and her checking her sole with a hand mirror.', 'Người phụ nữ ngồi trên ghế sofa kiểm tra bàn chân: hình bàn chân có dây thần kinh và vết thương nhỏ, và cảnh bà dùng gương soi lòng bàn chân.'),
  supplements: t('여성이 보충제 병을 들고 전문가와 이야기하는 장면. 식탁 위에 균형 잡힌 식사, 옆에 돋보기와 연구 자료.', 'The woman holds a supplement bottle and talks with a health professional. A balanced meal is on the table, with a magnifying glass and research papers nearby.', 'Người phụ nữ cầm lọ thực phẩm bổ sung và trò chuyện với chuyên gia y tế. Trên bàn có bữa ăn cân đối, bên cạnh là kính lúp và tài liệu nghiên cứu.')
};
for (const chapter of chapters) chapter.alt = imageAlt[chapter.id];
