import { t } from './book.mjs';
export const research = [
  { id: 'dpp', chapters: ['prevention'], title: 'DPP · Knowler et al. (2002)', url: 'https://doi.org/10.1056/NEJMoa012512',
    finding: t('고위험 성인에서 집중 생활습관 프로그램은 위약 대비 당뇨병 발생을 상대적으로 58%, 메트포르민은 31% 줄였습니다.', 'In high-risk adults, an intensive lifestyle program reduced diabetes incidence by 58% relative to placebo; metformin reduced it by 31%.', 'Ở người lớn nguy cơ cao, chương trình lối sống tích cực giảm tỷ lệ mắc đái tháo đường tương đối 58% so với giả dược; metformin giảm 31%.'),
    limit: t('고위험군의 구조화된 프로그램 결과이며, 개인의 절대 위험 감소나 일반적인 산책 효과와 같지 않습니다.', 'This was a structured program in a high-risk population, not an individual absolute risk reduction or the effect of ordinary walking.', 'Đây là chương trình có cấu trúc ở nhóm nguy cơ cao, không phải mức giảm nguy cơ tuyệt đối cá nhân hoặc hiệu quả đi bộ thông thường.') },
  { id: 'empa-kidney', chapters: ['medicines', 'feet'], title: 'EMPA-KIDNEY Collaborative Group (2023)', url: 'https://doi.org/10.1056/NEJMoa2204233',
    finding: t('만성콩팥병 연구에서 엠파글리플로진은 콩팥병 진행 또는 심혈관 사망의 복합 결과 위험을 위약 대비 낮췄습니다.', 'In chronic kidney disease, empagliflozin lowered the composite risk of kidney disease progression or cardiovascular death compared with placebo.', 'Trong bệnh thận mạn, empagliflozin giảm nguy cơ gộp tiến triển bệnh thận hoặc tử vong tim mạch so với giả dược.'),
    limit: t('특정 신장기능·위험 기준을 충족한 대상의 결과입니다. 모든 SGLT2 성분이나 모든 사람에게 같은 효과를 뜻하지 않습니다.', 'Participants met specific kidney and risk criteria. This does not imply the same effect for every SGLT2 ingredient or every person.', 'Người tham gia đáp ứng tiêu chí thận và nguy cơ cụ thể. Không có nghĩa mọi SGLT2 hoặc mọi người có hiệu quả giống nhau.') },
  { id: 'leader', chapters: ['medicines'], title: 'LEADER · Marso et al. (2016)', url: 'https://doi.org/10.1056/NEJMoa1603827',
    finding: t('심혈관 위험이 높은 2형 환자에서 리라글루타이드는 주요 심혈관 사건을 위약보다 줄였습니다.', 'Liraglutide reduced major cardiovascular events versus placebo in people with type 2 diabetes at high cardiovascular risk.', 'Liraglutide giảm biến cố tim mạch chính so với giả dược ở người típ 2 nguy cơ tim mạch cao.'),
    limit: t('리라글루타이드와 고위험군의 결과입니다. 혈당 저하만으로 모든 약의 심혈관 이익을 추론할 수 없습니다.', 'The finding concerns liraglutide and a high-risk population. Glucose lowering alone does not establish cardiovascular benefit for every medicine.', 'Kết quả về liraglutide và nhóm nguy cơ cao. Hạ đường huyết đơn thuần không chứng minh lợi ích tim mạch của mọi thuốc.') },
  { id: 'surpass2', chapters: ['medicines'], title: 'SURPASS-2 · Frías et al. (2021)', url: 'https://doi.org/10.1056/NEJMoa2107519',
    finding: t('메트포르민 치료 중인 2형 환자의 40주 비교에서 티르제파타이드는 세마글루타이드 1mg보다 HbA1c와 체중을 더 낮췄습니다.', 'In a 40-week comparison in metformin-treated type 2 diabetes, tirzepatide reduced HbA1c and weight more than semaglutide 1 mg.', 'Trong so sánh 40 tuần ở người típ 2 dùng metformin, tirzepatide giảm HbA1c và cân nặng nhiều hơn semaglutide 1 mg.'),
    limit: t('해당 용량·기간의 비교이며 모든 세마글루타이드 용량이나 심혈관 결과의 우월성을 입증한 연구가 아닙니다.', 'This compares specific doses and duration; it does not prove superiority to every semaglutide dose or superiority for cardiovascular outcomes.', 'So sánh ở liều và thời gian cụ thể; không chứng minh hơn mọi liều semaglutide hoặc hơn về kết quả tim mạch.') }
];
