import { t } from './book.mjs';
export const ui = {
  contextHeading: t('특정 상호작용만 확인하는 성분', 'Ingredients checked for selected interactions only', 'Hoạt chất chỉ kiểm tra một số tương tác'),
  contextNote: t('아래 성분은 레파글리니드와의 특정 상호작용만 확인합니다. 이 약들의 전체 부작용이나 다른 모든 병용 관계를 평가한 것은 아닙니다.', 'These ingredients are checked only for specific interactions with repaglinide. Their full adverse effects and all other combinations have not been assessed.', 'Các hoạt chất này chỉ được kiểm tra tương tác cụ thể với repaglinide. Chưa đánh giá toàn bộ tác dụng phụ và mọi phối hợp khác.'),
  cautionLibrary: t('약물 주의사항 찾아보기', 'Browse medicine cautions', 'Tra cứu lưu ý về thuốc'),
  cautionLibraryNote: t('다음은 검색 가능한 일반 참고자료입니다. 아래 항목 모두가 나에게 해당한다는 뜻은 아닙니다. 입력한 성분에 맞는 안내는 위의 성분 확인 결과에서 보세요.', 'This is a searchable general reference. These cautions do not all apply to you. See the ingredient results above for notices matched to your input.', 'Đây là tài liệu tham khảo chung có thể tìm kiếm. Không phải mọi lưu ý đều áp dụng cho bạn. Xem kết quả hoạt chất phía trên để biết lưu ý phù hợp với nội dung đã nhập.'),
  site: t('혈당과 함께 살아가기', 'Living well with blood glucose', 'Sống khỏe cùng đường huyết'),
  home: t('처음', 'Home', 'Trang chủ'),
  menu: t('목차', 'Contents', 'Mục lục'),
  tool: t('내 당뇨약 이해하기', 'Understand my medicines', 'Hiểu thuốc của tôi'),
  sources: t('근거와 업데이트', 'Evidence and updates', 'Bằng chứng và cập nhật'),
  book: t('전체 책 · PDF 저장', 'Full book · save PDF', 'Toàn sách · lưu PDF'),
  epub: t('EPUB 다운로드', 'Download EPUB', 'Tải EPUB'),
  print: t('인쇄 / PDF 저장', 'Print / save PDF', 'In / lưu PDF'),
  skip: t('본문 바로가기', 'Skip to content', 'Đến nội dung chính'),
  updated: t('근거 검토일', 'Evidence review date', 'Ngày xem xét bằng chứng'),
  action: t('오늘 할 행동', 'An action today', 'Hành động hôm nay'),
  caution: t('예외와 주의점', 'Exceptions and cautions', 'Ngoại lệ và lưu ý'),
  evidence: t('근거 펼쳐보기', 'Read the evidence', 'Xem bằng chứng'),
  illustration: t('이해를 돕는 교육용 일러스트', 'Illustration for education', 'Hình minh họa giáo dục'),
  disclaimer: t('이 책은 성인 전단계·2형 당뇨병의 일반적인 교육 자료입니다. 진단·처방·개인별 부작용 확률이나 약물 용량을 정하지 않습니다. 복약 변경은 의료진과 논의하세요.', 'This book provides general education about adult prediabetes and type 2 diabetes. It does not diagnose, prescribe or determine individual adverse-event probabilities or doses. Discuss medication changes with your care team.', 'Sách cung cấp giáo dục chung về tiền đái tháo đường và típ 2 ở người lớn. Không chẩn đoán, kê đơn hay tính xác suất tác dụng phụ và liều cá nhân. Trao đổi thay đổi thuốc với nhóm chăm sóc.'),
  emergency: t('한국 응급전화 119 · 해외에서는 현지 응급번호를 사용하세요.', 'Use the local emergency number: 119 in Korea, 115 for ambulance services in Vietnam; numbers vary elsewhere.', 'Cấp cứu: 115 cho xe cấp cứu tại Việt Nam, 119 tại Hàn Quốc; nơi khác dùng số địa phương.'),
  intro: t('나와 가족을 위한 당뇨 안내서', 'A diabetes guide for you and your family', 'Hướng dẫn đái tháo đường cho bạn và gia đình'),
  hero: t('검사 수치에서 식단·운동·약의 원리까지. 쉬운 설명과 같은 여성 캐릭터의 그림으로 한 주제씩 읽어보세요.', 'From test results to food, activity and medicine mechanisms. Read one topic at a time with clear explanations and consistent illustrations.', 'Từ xét nghiệm đến ăn uống, vận động và cơ chế thuốc. Đọc từng chủ đề với giải thích rõ ràng và hình minh họa nhất quán.'),
  start: t('첫 주제부터 읽기', 'Start reading', 'Bắt đầu đọc'),
  font: t('글자 크기', 'Text size', 'Cỡ chữ'),
  fontNormal: t('보통', 'Normal', 'Vừa'),
  fontLarge: t('크게', 'Large', 'Lớn'),
  fontXlarge: t('아주 크게', 'Extra large', 'Rất lớn'),
  keyPoints: t('이것만 기억하세요', 'Remember these', 'Những điều cần nhớ'),
  summary: t('한눈에 보기', 'At a glance', 'Tóm tắt nhanh'),
  summaryIntro: t('주제마다 꼭 기억할 내용만 모았습니다. 자세한 설명과 예외는 각 주제에서 확인하세요. 인쇄해서 냉장고에 붙여 두어도 좋습니다.', 'The most important points from each topic. See each topic for details and exceptions. You can print this page and keep it at home.', 'Những điểm quan trọng nhất của từng chủ đề. Xem chi tiết và ngoại lệ trong từng chủ đề. Có thể in trang này và để ở nhà.'),
  readMore: t('자세히 읽기', 'Read the full topic', 'Đọc chi tiết'),
  search: t('책 전체 검색', 'Search the book', 'Tìm trong sách'),
  searchPlaceholder: t('예: 저혈당, 발, 메트포르민', 'Example: hypoglycemia, feet, metformin', 'Ví dụ: hạ đường huyết, bàn chân, metformin'),
  noSearch: t('검색 결과가 없습니다.', 'No matching sections.', 'Không có phần phù hợp.'),
  resume: t('읽던 위치로 돌아가기', 'Resume reading', 'Đọc tiếp vị trí trước'),
  clearResume: t('읽기 기록 지우기', 'Clear reading history', 'Xóa lịch sử đọc'),
  next: t('다음 주제', 'Next topic', 'Chủ đề tiếp theo'),
  previous: t('이전 주제', 'Previous topic', 'Chủ đề trước'),
  input: t('약봉투의 성분명 (여러 개 가능)', 'Ingredient names from your prescription', 'Tên hoạt chất trên đơn thuốc'),
  inputHelp: t('성분 사이에 +, 쉼표, / 또는 줄바꿈을 사용하세요. 예: 메트포르민 500mg + 시타글립틴 50mg. 제품명은 자동 추정하지 않습니다. 함량·제형은 위험 계산에 사용하지 않으므로 처방대로 확인하세요.', 'Separate ingredients with +, comma, / or a new line. Example: metformin 500mg + sitagliptin 50mg. Brand names are not guessed. Strength and formulation do not enter a risk calculation; follow your prescription.', 'Ngăn hoạt chất bằng +, dấu phẩy, / hoặc xuống dòng. Ví dụ: metformin 500mg + sitagliptin 50mg. Không đoán tên thương mại. Hàm lượng, dạng thuốc không dùng tính nguy cơ; theo đơn của bạn.'),
  placeholder: t('메트포르민 500mg + 시타글립틴 50mg', 'metformin 500mg + sitagliptin 50mg', 'metformin 500mg + sitagliptin 50mg'),
  analyze: t('성분 확인하기', 'Check ingredients', 'Kiểm tra hoạt chất'),
  reset: t('입력 지우기', 'Clear input', 'Xóa nhập liệu'),
  sample: t('예시 넣기', 'Load example', 'Điền ví dụ'),
  renal: t('콩팥 기능 저하를 진단받았습니다 (선택)', 'Diagnosed kidney impairment (optional)', 'Đã được chẩn đoán suy giảm chức năng thận (tùy chọn)'),
  heart: t('심부전 병력이 있습니다 (선택)', 'History of heart failure (optional)', 'Có tiền sử suy tim (tùy chọn)'),
  privacy: t('성분·건강 선택값은 이 브라우저에서만 처리하며 저장·전송하지 않습니다. 읽기 위치와 글자 크기만 기기에 저장됩니다.', 'Ingredients and health selections are processed only in this browser, without saving or transmission. Only reading position and text size are stored on the device.', 'Hoạt chất và lựa chọn sức khỏe chỉ xử lý trong trình duyệt, không lưu hay gửi. Chỉ vị trí đọc và cỡ chữ được lưu trên thiết bị.'),
  scope: t('현재 42개 당뇨약 성분의 계열 정보를 제공합니다. 모든 신약·제품·상호작용을 포함하지 않습니다. 겜피브로질·클로피도그렐은 레파글리니드 관련 확인용입니다. 국적·언어는 허가 국가를 의미하지 않습니다.', 'Currently provides class information for 42 diabetes ingredients. It does not cover every new medicine, product or interaction. Gemfibrozil and clopidogrel are recognized for repaglinide checks. Language does not imply national approval.', 'Hiện cung cấp thông tin nhóm cho 42 hoạt chất đái tháo đường. Không bao gồm mọi thuốc mới, sản phẩm hoặc tương tác. Gemfibrozil và clopidogrel được nhận diện để kiểm tra repaglinide. Ngôn ngữ không hàm ý được cấp phép tại nước đó.'),
  recognized: t('확인된 성분', 'Recognized ingredients', 'Hoạt chất nhận diện được'),
  unknown: t('확인되지 않은 입력', 'Unverified input', 'Nội dung chưa xác định'),
  suggestion: t('비슷한 성분명 후보 (자동 선택하지 않음)', 'Similar names to check (not selected automatically)', 'Tên gần giống để kiểm tra (không tự chọn)'),
  noRules: t('등록된 조합 주의 규칙에 해당하지 않았습니다. 이것은 안전 판정이 아니며, 다른 약·용량·병력은 별도 검토가 필요합니다.', 'No registered combination rule matched. This is not a safety clearance; other medicines, doses and medical history need separate review.', 'Không khớp quy tắc phối hợp đã đăng ký. Đây không phải kết luận an toàn; thuốc khác, liều và bệnh sử cần xem riêng.'),
  nothing: t('약봉투의 성분명을 먼저 입력하세요.', 'Enter ingredient names first.', 'Nhập tên hoạt chất trước.'),
  tooLong: t('입력은 4,000자 이내로 작성하세요.', 'Use no more than 4,000 characters.', 'Nhập tối đa 4.000 ký tự.'),
  noKnown: t('당뇨약 성분을 확인하지 못했습니다. 제품명 대신 정확한 성분명을 입력하세요.', 'No diabetes ingredient was recognized. Enter exact ingredient names rather than brand names.', 'Không nhận diện được hoạt chất đái tháo đường. Nhập tên hoạt chất chính xác thay tên thương mại.'),
  mechanism: t('작용기전', 'Mechanism', 'Cơ chế'),
  benefit: t('기대 이익', 'Expected benefits', 'Lợi ích mong đợi'),
  common: t('흔하거나 알려진 증상', 'Common or reported effects', 'Tác dụng thường gặp hoặc đã báo cáo'),
  serious: t('중요한 위험·경고', 'Important risks and warnings', 'Nguy cơ và cảnh báo quan trọng'),
  lifestyle: t('식사·운동·생활 확인', 'Food, activity and daily-life checks', 'Lưu ý ăn uống, vận động và sinh hoạt'),
  ruleHeading: t('조합·상황별 확인할 사항', 'Combination and context checks', 'Điểm cần kiểm tra theo phối hợp và tình trạng'),
  class: t('약물 계열', 'Medicine class', 'Nhóm thuốc'),
  catalog: t('지원 성분명 목록', 'Supported ingredient names', 'Danh sách hoạt chất hỗ trợ'),
  sourceIntro: t('핵심 설명을 지침·허가사항·문헌고찰과 연결합니다. 근거 종류와 확실성은 같지 않습니다. 허가사항 경고는 발생 확률이나 인과관계 확정을 뜻하지 않습니다.', 'Core explanations link to guidelines, labels and systematic reviews. Source type is not the same as certainty. A label warning is not a personal probability or proof of causation.', 'Giải thích chính liên kết hướng dẫn, nhãn thuốc và tổng quan hệ thống. Loại nguồn không đồng nghĩa độ chắc chắn. Cảnh báo nhãn không phải xác suất cá nhân hay chứng minh nhân quả.'),
  evidencePolicy: t('근거를 읽는 기준', 'How we interpret evidence', 'Cách hiểu bằng chứng'),
  evidenceText: t('지침 권고, 임상시험의 효과, 관찰연구의 연관성, 허가사항의 경고를 구분합니다. 대상·기간·비교군·결과지표를 확인하고, 혈당 수치 개선과 합병증 예방을 따로 설명합니다. 근거의 확실성이 제한된 경우 본문에 한계를 표시합니다.', 'We distinguish guideline recommendations, trial effects, observational associations and label warnings. We consider population, duration, comparison and outcome, separating glucose changes from prevention of complications. Limited certainty is described in the text.', 'Phân biệt khuyến nghị hướng dẫn, hiệu quả thử nghiệm, liên hệ quan sát và cảnh báo nhãn. Xem đối tượng, thời gian, nhóm so sánh, kết quả; tách thay đổi đường huyết khỏi phòng biến chứng. Nêu giới hạn khi độ chắc chắn hạn chế.'),
  updateText: t('원문과 번역은 같은 주제·문단 ID를 공유합니다. 한국어 원문이 바뀌면 영어·베트남어의 검토 상태가 바뀌며, 배포 검사에서 누락을 확인합니다. 새로운 근거를 자동 수집해 게시하는 기능은 없습니다.', 'Original and translations share topic and section IDs. Changes to Korean source content invalidate English and Vietnamese review status and are checked before release. There is no automatic research collection or publishing.', 'Bản gốc và bản dịch dùng chung ID chủ đề, đoạn. Thay đổi bản Hàn làm mất hiệu lực trạng thái duyệt Anh, Việt và được kiểm tra trước phát hành. Không tự thu thập hay đăng nghiên cứu.'),
  translation: t('번역은 교육용 초안이며 의료 전문 번역의 별도 검수를 완료한 자료는 아닙니다.', 'Translations are educational drafts; independent medical translation review has not been completed.', 'Bản dịch là bản giáo dục dự thảo; chưa hoàn tất thẩm định dịch y khoa độc lập.'),
  stale: t('원문 변경으로 번역 재검토가 필요합니다.', 'Translation review required after source changes.', 'Cần duyệt lại bản dịch sau thay đổi bản gốc.'),
  faq: t('자주 묻는 질문', 'Frequently asked questions', 'Câu hỏi thường gặp'),
  faqItems: [
    { q: t('수치가 좋아지면 약을 끊어도 되나요?', 'Can I stop medicines when readings improve?', 'Có thể ngừng thuốc khi số đo tốt hơn không?'), a: t('약과 생활습관의 효과일 수 있습니다. 관해 가능성을 포함해 의료진과 논의하고 임의로 끊지 마세요.', 'Improved readings may reflect medicines and lifestyle. Discuss changes, including possible remission, with your care team.', 'Số đo tốt hơn có thể nhờ thuốc và lối sống. Trao đổi thay đổi, kể cả khả năng thuyên giảm, với nhóm chăm sóc.') },
    { q: t('당뇨병이면 과일을 못 먹나요?', 'Is fruit forbidden?', 'Đái tháo đường có phải kiêng trái cây không?'), a: t('통과일도 식단에 포함할 수 있습니다. 양과 총 탄수화물, 개인 혈당 반응을 함께 살피세요.', 'Whole fruit can fit a meal plan. Consider portions, total carbohydrate and individual responses.', 'Có thể đưa trái cây nguyên quả vào kế hoạch ăn. Xem khẩu phần, tổng carbohydrate và đáp ứng cá nhân.') },
    { q: t('부작용 목록에 있으면 내 증상도 약 때문인가요?', 'Does a listed adverse effect prove my symptom is from the medicine?', 'Có tác dụng phụ trong danh sách thì triệu chứng của tôi do thuốc phải không?'), a: t('그렇지 않습니다. 질병·다른 약·복용 시점 등 여러 원인을 검토해야 합니다. 심하거나 지속되는 증상은 진료로 확인하세요.', 'No. Illness, other medicines and timing need consideration. Severe or persistent symptoms need assessment.', 'Không. Cần xét bệnh, thuốc khác và thời điểm dùng. Triệu chứng nặng hoặc kéo dài cần đánh giá.') }
  ],
  types: {
    guideline: t('진료지침', 'Clinical guideline', 'Hướng dẫn lâm sàng'),
    review: t('체계적 문헌고찰', 'Systematic review', 'Tổng quan hệ thống'),
    label: t('미국 허가사항', 'US prescribing information', 'Thông tin kê đơn Hoa Kỳ'),
    regulator: t('국내 허가사항 검색', 'Korean product label search', 'Tra cứu nhãn thuốc Hàn Quốc'),
    patient: t('공공기관 환자교육', 'Public patient education', 'Giáo dục bệnh nhân từ cơ quan công')
  }
};
